In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [8]:
df.shape

(303, 14)

In [9]:
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
273    0
274    0
275    0
276    0
277    0
278    0
279    0
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    0
288    0
289    0
290    0
291    0
292    0
293    0
294    0
295    0
296    0
297    0
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [10]:
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca']
X = df[features]
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca
0,63,1,3,145,233,1,0,150,0,2.3,0,0
1,37,1,2,130,250,0,1,187,0,3.5,0,0
2,41,0,1,130,204,0,0,172,0,1.4,2,0
3,56,1,1,120,236,0,1,178,0,0.8,2,0
4,57,0,0,120,354,0,1,163,1,0.6,2,0
5,57,1,0,140,192,0,1,148,0,0.4,1,0
6,56,0,1,140,294,0,0,153,0,1.3,1,0
7,44,1,1,120,263,0,1,173,0,0.0,2,0
8,52,1,2,172,199,1,1,162,0,0.5,2,0
9,57,1,2,150,168,0,1,174,0,1.6,2,0
10,54,1,0,140,239,0,1,160,0,1.2,2,0
11,48,0,2,130,275,0,1,139,0,0.2,2,0
12,49,1,1,130,266,0,1,171,0,0.6,2,0
13,64,1,3,110,211,0,0,144,1,1.8,1,0
14,58,0,3,150,283,1,0,162,0,1.0,2,0
15,50,0,2,120,219,0,1,158,0,1.6,1,0
16,58,0,2,120,340,0,1,172,0,0.0,2,0
17,66,0,3,150,226,0,1,114,0,2.6,0,0
18,43,1,0,150,247,0,1,171,0,1.5,2,0
19,69,0,3,140,239,0,1,151,0,1.8,2,2
20,59,1,0,135,234,0,1,161,0,0.5,1,0
21,44,1,2,130,233,0,1,179,1,0.4,2,0
22,42,1,0,140,226,0,1,178,0,0.0,2,0
23,61,1,2,150,243,1,1,137,1,1.0,1,0
24,40,1,3,140,199,0,1,178,1,1.4,2,0
25,71,0,1,160,302,0,1,162,0,0.4,2,2
26,59,1,2,150,212,1,1,157,0,1.6,2,0
27,51,1,2,110,175,0,1,123,0,0.6,2,0
28,65,0,2,140,417,1,0,157,0,0.8,2,1
29,53,1,2,130,197,1,0,152,0,1.2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
273,58,1,0,100,234,0,1,156,0,0.1,2,1
274,47,1,0,110,275,0,0,118,1,1.0,1,1
275,52,1,0,125,212,0,1,168,0,1.0,2,2
276,58,1,0,146,218,0,1,105,0,2.0,1,1
277,57,1,1,124,261,0,1,141,0,0.3,2,0
278,58,0,1,136,319,1,0,152,0,0.0,2,2
279,61,1,0,138,166,0,0,125,1,3.6,1,1
280,42,1,0,136,315,0,1,125,1,1.8,1,0
281,52,1,0,128,204,1,1,156,1,1.0,1,0
282,59,1,2,126,218,1,1,134,0,2.2,1,1
283,40,1,0,152,223,0,1,181,0,0.0,2,0
284,61,1,0,140,207,0,0,138,1,1.9,2,1
285,46,1,0,140,311,0,1,120,1,1.8,1,2
286,59,1,3,134,204,0,1,162,0,0.8,2,2
287,57,1,1,154,232,0,0,164,0,0.0,2,1
288,57,1,0,110,335,0,1,143,1,3.0,1,1
289,55,0,0,128,205,0,2,130,1,2.0,1,1
290,61,1,0,148,203,0,1,161,0,0.0,2,1
291,58,1,0,114,318,0,2,140,0,4.4,0,3
292,58,0,0,170,225,1,0,146,1,2.8,1,2
293,67,1,2,152,212,0,0,150,0,0.8,1,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2
296,63,0,0,124,197,0,1,136,1,0.0,1,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2
298,57,0,0,140,241,0,1,123,1,0.2,1,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2
301,57,1,0,130,131,0,1,115,1,1.2,1,1
302,57,0,1,130,236,0,0,174,0,0.0,1,1

In [11]:
X.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000

In [12]:
from sklearn.tree import DecisionTreeRegressor

In [13]:
target_model = DecisionTreeRegressor (random_state=1)

In [14]:
target_model.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=1, splitter='best')

In [15]:
target_model.predict(X.head())

array([1., 1., 1., 1., 1.])

In [16]:
c

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [18]:
y_hat = target_model.predict(X)
mean_absolute_error (y, y_hat)

0.0

In [19]:
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.1)
y_train.head()

101    1
170    0
238    0
10     1
48     1
Name: target, dtype: int64

In [20]:
target_model = DecisionTreeRegressor (random_state = 1)
target_model.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=1, splitter='best')

In [21]:
y_hat = target_model.predict(X_test)
mean_absolute_error (y_test, y_hat)

0.25806451612903225

In [22]:
def get_mae (max_leaf_nodes, X_train, X_test, y_train, y_test):
    target_model = DecisionTreeRegressor (max_leaf_nodes=max_leaf_nodes, random_state = 1)
    target_model.fit(X_train, y_train)
    y_hat = target_model.predict(X_test)
    mae = mean_absolute_error (y_test, y_hat)
    return mae

In [24]:
for max_leaf_nodes in [2, 4, 7, 10] :
    leaf_mae = get_mae (max_leaf_nodes, X_train, X_test, y_train, y_test)
    print (f' Max leaf nodes : {max_leaf_nodes} \t Mean Absolute Error : {int(leaf_mae)}')

 Max leaf nodes : 2 	 Mean Absolute Error : 0
 Max leaf nodes : 4 	 Mean Absolute Error : 0
 Max leaf nodes : 7 	 Mean Absolute Error : 0
 Max leaf nodes : 10 	 Mean Absolute Error : 0

In [25]:
rf_df = RandomForestRegressor (n_estimators=50, random_state = 1)
rf_df.fit (X_train, y_train)
y_hat = rf_df.predict(X_test)
print (f'Mean Absolute Error:{int(mean_absolute_error(y_test, y_hat))}')

Mean Absolute Error:0